ff

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,3 +1,12 @@
 #!/bin/bash
 
-echo "Test Hook"
+echo "Testing........"
+OUTPUT="$(go test ./...)"
+if [ $? -ne 0 ]
+then
+	echo "${OUTPUT}"
+	echo "Failed to run tests. Please check the output of"
+	echo "go test or run commit with --no-verify if you know"
+	echo "what you are doing."
+	exit 1
+fi
